### ISSUE TITLE
Améliorer l'accessibilité

### ISSUE THREAD

**Issue by augnustin** [cowork-in-montpellier/cowork-in-montpellier#10]
- [ ] Prendre en compte les retours automatiques : https://pagespeed.web.dev/analysis/https-coworkinmontpellier-org/wr8ocr2dam?utm_source=search_console&form_factor=mobile&hl=fr
- [ ] autres ?

**Comment by newick** [comment]
en coup d’œil rapide : 
- [x] lier les labels et les inputs avec for et id
- [x] mettre des textes cachés sur les liens icônes 
- [x] utiliser des sections à la place des divs pour ajouter de la sémantique
- [x] pareil footer à la place de div
- [x] les icônes font awesome devraient avoir `aria-hidden: true`
